// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Android ─────────────────────────────────────────────────────────────
  // Values sourced from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi3PDAqcPwRuwoKCKYRM7X1077TqW-JoA',
    appId: '1:594776252575:android:52f7b431ec6d15aa5842aa',
    messagingSenderId: '594776252575',
    projectId: 'lexguard-ai-e91b7',
    storageBucket: 'lexguard-ai-e91b7.firebasestorage.app',
  );

  // ── Web ──────────────────────────────────────────────────────────────────
  // TODO: Register a Web app in Firebase Console and replace these values.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3PDAqcPwRuwoKCKYRM7X1077TqW-JoA',
    appId: '1:594776252575:web:cba88686d1bf2b935842aa',
    messagingSenderId: '594776252575',
    projectId: 'lexguard-ai-e91b7',
    authDomain: 'lexguard-ai-e91b7.firebaseapp.com',
    storageBucket: 'lexguard-ai-e91b7.firebasestorage.app',
    measurementId: 'G-E91B7XXXXX',
  );

  // ── iOS ──────────────────────────────────────────────────────────────────
  // TODO: Download GoogleService-Info.plist from Firebase Console and replace these values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '594776252575',
    projectId: 'lexguard-ai-e91b7',
    storageBucket: 'lexguard-ai-e91b7.firebasestorage.app',
    iosBundleId: 'com.lexguard.lexguardAi',
  );

  // ── macOS ────────────────────────────────────────────────────────────────
  // TODO: Register a macOS app in Firebase Console and replace these values.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: 'REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: '594776252575',
    projectId: 'lexguard-ai-e91b7',
    storageBucket: 'lexguard-ai-e91b7.firebasestorage.app',
    iosBundleId: 'com.lexguard.lexguardAi',
  );

  // ── Windows ──────────────────────────────────────────────────────────────
  // TODO: Register a Windows app in Firebase Console and replace these values.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi3PDAqcPwRuwoKCKYRM7X1077TqW-JoA',
    appId: 'REPLACE_WITH_WINDOWS_APP_ID',
    messagingSenderId: '594776252575',
    projectId: 'lexguard-ai-e91b7',
    authDomain: 'lexguard-ai-e91b7.firebaseapp.com',
    storageBucket: 'lexguard-ai-e91b7.firebasestorage.app',
    measurementId: 'REPLACE_WITH_MEASUREMENT_ID',
  );
}
